// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_encounter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// 一份文档当前的「已确认」状态(医生代拍待确认列表)。**不**塞进共享的
/// `DocumentSummaryDto`(`vault.rs` 的正常病人档案列表也用它,这个状态只对医生
/// 代拍流程有意义)——待确认列表屏用 `document_id` 把这份状态与
/// `ephemeral_load_preview` 返回的文档列表在 Dart 侧做本地映射。由
/// `api::vault_ephemeral::ephemeral_confirmed_map` 产出。
class ConfirmedStatusDto {
  final PlatformInt64 documentId;
  final bool confirmed;

  const ConfirmedStatusDto({required this.documentId, required this.confirmed});

  @override
  int get hashCode => documentId.hashCode ^ confirmed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfirmedStatusDto &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          confirmed == other.confirmed;
}

/// 拍前同意记录(医生代拍病人纸质材料流程):病人同意的方式(手写签名 / 按住
/// 确认)、时刻、文案版本。由 `screens/doctor/consent_screen.dart` 产出,经
/// `api::vault_ephemeral::ephemeral_create_share` 转换成
/// `medme_share::share::ShareConsent` 塞进加密分享包(见该函数的 `From` 实现)。
class ConsentDto {
  /// 同意时刻(UTC RFC3339)。
  final String utcTs;

  /// 同意告知文案的版本号(见 `consent_screen.dart` 的 `kConsentTextVersion`)。
  final String consentTextVersion;

  /// 手写签名 PNG 的 base64;按住确认(无签名图像)时为 `None`。
  final String? signaturePngBase64;

  /// "signature" | "press_hold"。
  final String method;

  /// 本次临时会话的人类可读标识,供医生/病人事后核对「哪一次代建档」
  /// (不是安全边界——临时会话的一次性随机 device_id 才是,见 `vault_ephemeral.rs`)。
  final String sessionId;

  const ConsentDto({
    required this.utcTs,
    required this.consentTextVersion,
    this.signaturePngBase64,
    required this.method,
    required this.sessionId,
  });

  @override
  int get hashCode =>
      utcTs.hashCode ^
      consentTextVersion.hashCode ^
      signaturePngBase64.hashCode ^
      method.hashCode ^
      sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConsentDto &&
          runtimeType == other.runtimeType &&
          utcTs == other.utcTs &&
          consentTextVersion == other.consentTextVersion &&
          signaturePngBase64 == other.signaturePngBase64 &&
          method == other.method &&
          sessionId == other.sessionId;
}

/// 文档详情:类型/日期(在 document 里)+ 来源文件 + 识别文本。
class DocumentDetailDto {
  final DocumentSummaryDto document;
  final SourceFileMetaDto sourceFile;
  final String ocrText;
  final double? ocrConfidence;
  final String? ocrBackend;

  const DocumentDetailDto({
    required this.document,
    required this.sourceFile,
    required this.ocrText,
    this.ocrConfidence,
    this.ocrBackend,
  });

  @override
  int get hashCode =>
      document.hashCode ^
      sourceFile.hashCode ^
      ocrText.hashCode ^
      ocrConfidence.hashCode ^
      ocrBackend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentDetailDto &&
          runtimeType == other.runtimeType &&
          document == other.document &&
          sourceFile == other.sourceFile &&
          ocrText == other.ocrText &&
          ocrConfidence == other.ocrConfidence &&
          ocrBackend == other.ocrBackend;
}

class DocumentSummaryDto {
  final PlatformInt64 id;
  final String docType;
  final String? docDate;
  final String? docDateEnd;
  final String? title;
  final int pageCount;

  /// 影像检查文档的切片数;非影像文档为 None。
  final int? sliceCount;

  const DocumentSummaryDto({
    required this.id,
    required this.docType,
    this.docDate,
    this.docDateEnd,
    this.title,
    required this.pageCount,
    this.sliceCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      docType.hashCode ^
      docDate.hashCode ^
      docDateEnd.hashCode ^
      title.hashCode ^
      pageCount.hashCode ^
      sliceCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          docType == other.docType &&
          docDate == other.docDate &&
          docDateEnd == other.docDateEnd &&
          title == other.title &&
          pageCount == other.pageCount &&
          sliceCount == other.sliceCount;
}

class EncounterSummaryDto {
  final PlatformInt64 id;
  final String kind;
  final String? provider;
  final String? startDate;
  final String? endDate;
  final String? title;
  final bool transferred;
  final PlatformInt64 docCount;

  const EncounterSummaryDto({
    required this.id,
    required this.kind,
    this.provider,
    this.startDate,
    this.endDate,
    this.title,
    required this.transferred,
    required this.docCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      provider.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      title.hashCode ^
      transferred.hashCode ^
      docCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncounterSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          provider == other.provider &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          title == other.title &&
          transferred == other.transferred &&
          docCount == other.docCount;
}

/// 时间线导出结果:未加密、可打印的自包含 HTML。与 `ShareResultDto` 不同,
/// 没有口令——导出内容不加密,靠系统「分享」sheet 直接交给医生 / 存下来打印。
class ExportResultDto {
  final PlatformInt64 recordCount;
  final PlatformInt64 byteSize;
  final String path;

  const ExportResultDto({
    required this.recordCount,
    required this.byteSize,
    required this.path,
  });

  @override
  int get hashCode => recordCount.hashCode ^ byteSize.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportResultDto &&
          runtimeType == other.runtimeType &&
          recordCount == other.recordCount &&
          byteSize == other.byteSize &&
          path == other.path;
}

/// iCloud 同步状态(设置页开关据此渲染)。`available` = 当前能否解析到 iCloud
/// 容器(iOS-only,由 Dart 侧经 `medme/icloud` MethodChannel 判断后覆盖;Rust
/// 恒返回 false);`enabled` = 本设备是否已开启同步(Rust 据持久标记返回)。
/// 开关/迁移逻辑见 `api::vault` 的 `enable_icloud_sync` / `disable_icloud_sync`。
class IcloudStatusDto {
  final bool available;
  final bool enabled;

  const IcloudStatusDto({required this.available, required this.enabled});

  @override
  int get hashCode => available.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IcloudStatusDto &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          enabled == other.enabled;
}

class ImportOutcomeDto {
  final String name;
  final PlatformInt64 sourceFileId;
  final String status;
  final String? docType;

  /// 本次采集落库的文档 id(前端「待确认」review 队列据此显式标记新导入)。
  /// 去重/失败等没建文档的情况为 None。
  final PlatformInt64? documentId;

  /// 从本份报告文本里识别出的**患者姓名**(`parser::extract_demographics`)。
  /// 前端用它和当前成员档案名字比对——不一致就在「待确认」里标红警告(防导错人)。
  /// 识别不到为 None。
  final String? detectedName;

  const ImportOutcomeDto({
    required this.name,
    required this.sourceFileId,
    required this.status,
    this.docType,
    this.documentId,
    this.detectedName,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      sourceFileId.hashCode ^
      status.hashCode ^
      docType.hashCode ^
      documentId.hashCode ^
      detectedName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportOutcomeDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sourceFileId == other.sourceFileId &&
          status == other.status &&
          docType == other.docType &&
          documentId == other.documentId &&
          detectedName == other.detectedName;
}

/// **iOS PP-OCRv5 测试路径**结果(feat/ios-pp-ocr-test 分支,探索性——ADR 0005
/// 尚未 supersede)。镜像 Dart `OcrResult`(`ocr_bridge.dart`),供
/// `recognize_image_pp` 返回,让真机能对比 Apple Vision vs PP-OCRv5 的识别质量。
class OcrPpResultDto {
  final String text;
  final double confidence;

  const OcrPpResultDto({required this.text, required this.confidence});

  @override
  int get hashCode => text.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrPpResultDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          confidence == other.confidence;
}

class PatientProfileDto {
  final String? name;
  final String? gender;
  final String? birthDate;
  final String? age;
  final PlatformInt64 recordCount;

  const PatientProfileDto({
    this.name,
    this.gender,
    this.birthDate,
    this.age,
    required this.recordCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      gender.hashCode ^
      birthDate.hashCode ^
      age.hashCode ^
      recordCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatientProfileDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          gender == other.gender &&
          birthDate == other.birthDate &&
          age == other.age &&
          recordCount == other.recordCount;
}

/// 一条化验序列:最近值 + 趋势 + 最近几个点(≤4,时间升序)。没有任何带日期的点
/// (`assemble_summary` 的 `pts` 只保留带日期的观测)时不产出——审阅屏没法从中读出
/// 「最近值」,原始识别文字仍在下方「逐份识别内容」区块里,不丢信息。
class ProxyLabDto {
  final String name;
  final String? unit;
  final double latestValue;
  final double? refHigh;
  final double? refLow;

  /// "up" | "down" | "flat" | "single"(只有一个带日期的点,不足以判断趋势)。
  final String trend;
  final List<ProxyLabPointDto> recentPoints;

  const ProxyLabDto({
    required this.name,
    this.unit,
    required this.latestValue,
    this.refHigh,
    this.refLow,
    required this.trend,
    required this.recentPoints,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      unit.hashCode ^
      latestValue.hashCode ^
      refHigh.hashCode ^
      refLow.hashCode ^
      trend.hashCode ^
      recentPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyLabDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          unit == other.unit &&
          latestValue == other.latestValue &&
          refHigh == other.refHigh &&
          refLow == other.refLow &&
          trend == other.trend &&
          recentPoints == other.recentPoints;
}

class ProxyLabPointDto {
  /// "YYYY-MM"。
  final String month;
  final double value;

  const ProxyLabPointDto({required this.month, required this.value});

  @override
  int get hashCode => month.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyLabPointDto &&
          runtimeType == other.runtimeType &&
          month == other.month &&
          value == other.value;
}

/// 一条在用药:名 + 最近一次提到的剂量(若识别到)+ 是否在用。字段名 `active`
/// 而不是 `assemble_summary` json 里的 `on`——后者是 Dart 的保留字上下文关键字,
/// FRB codegen 会把它改名成 `on_`,不如从 Rust 侧就用一个干净的名字。
class ProxyMedDto {
  final String name;
  final String? dose;
  final bool active;

  const ProxyMedDto({required this.name, this.dose, required this.active});

  @override
  int get hashCode => name.hashCode ^ dose.hashCode ^ active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyMedDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          dose == other.dose &&
          active == other.active;
}

/// 一条在治问题:名字 + 状态,嵌套它的关键化验与在用药。
class ProxyProblemDto {
  final String term;

  /// "在管" | "需关注" | "其他"(未挂上具体疾病的化验/用药落这个桶,见
  /// `parser::handoff::assemble_summary` 的「其他」bucket)。
  final String status;
  final bool warn;
  final List<ProxyLabDto> labs;
  final List<ProxyMedDto> meds;

  const ProxyProblemDto({
    required this.term,
    required this.status,
    required this.warn,
    required this.labs,
    required this.meds,
  });

  @override
  int get hashCode =>
      term.hashCode ^
      status.hashCode ^
      warn.hashCode ^
      labs.hashCode ^
      meds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyProblemDto &&
          runtimeType == other.runtimeType &&
          term == other.term &&
          status == other.status &&
          warn == other.warn &&
          labs == other.labs &&
          meds == other.meds;
}

/// 「病情摘要卡」(医生代拍审阅屏,选项 b):在治的病 + 关键化验 + 在用药,
/// 三十秒看懂大局。由 `api::vault_ephemeral::ephemeral_summary` 产出——把
/// `parser::assemble_summary` 的通用 `serde_json::Value`(查看器/加密分享用的同一份
/// 装配逻辑)映射成 FRB 能直接生成 Dart 绑定的定型结构。**不做 QR 分享那种带宽裁剪**
/// (`medme_share::qr::trim_summary` 的 `max_problems`/`active_meds_only` 等是为
/// 二维码容量服务的,审阅屏要的是「拍了什么就看到什么」的完整核对,不是带宽约束)——
/// 唯一的裁剪是每条化验只保留最近 4 个点,与 `notable_changes`/QR 默认档同一惯例
/// (给「趋势一眼」用,不是画完整图表)。
class ProxySummaryDto {
  final List<ProxyProblemDto> problems;

  const ProxySummaryDto({required this.problems});

  @override
  int get hashCode => problems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxySummaryDto &&
          runtimeType == other.runtimeType &&
          problems == other.problems;
}

/// 二维码分享结果:一条可直接编码成二维码的 URL、带上的疾病数、以及是否仍在
/// 二维码容量内(按构造裁剪后应恒为 true,留作兜底提示)。
class QrShareDto {
  final String url;
  final PlatformInt64 problemCount;
  final bool fitsQr;

  const QrShareDto({
    required this.url,
    required this.problemCount,
    required this.fitsQr,
  });

  @override
  int get hashCode => url.hashCode ^ problemCount.hashCode ^ fitsQr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrShareDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          problemCount == other.problemCount &&
          fitsQr == other.fitsQr;
}

/// 加密分享生成结果:口令(单独告知医生)、记录数、文件字节数、分享文件路径。
class ShareResultDto {
  final String passphrase;
  final PlatformInt64 recordCount;
  final PlatformInt64 byteSize;
  final String path;

  const ShareResultDto({
    required this.passphrase,
    required this.recordCount,
    required this.byteSize,
    required this.path,
  });

  @override
  int get hashCode =>
      passphrase.hashCode ^
      recordCount.hashCode ^
      byteSize.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareResultDto &&
          runtimeType == other.runtimeType &&
          passphrase == other.passphrase &&
          recordCount == other.recordCount &&
          byteSize == other.byteSize &&
          path == other.path;
}

/// 原始文件元信息(文档详情页展示来源 + 前端据此判断是否为图片以渲染缩略)。
class SourceFileMetaDto {
  final PlatformInt64 id;
  final String originalName;
  final String mimeType;
  final PlatformInt64 byteSize;
  final String importedAt;

  const SourceFileMetaDto({
    required this.id,
    required this.originalName,
    required this.mimeType,
    required this.byteSize,
    required this.importedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      originalName.hashCode ^
      mimeType.hashCode ^
      byteSize.hashCode ^
      importedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceFileMetaDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          originalName == other.originalName &&
          mimeType == other.mimeType &&
          byteSize == other.byteSize &&
          importedAt == other.importedAt;
}

@freezed
sealed class TimelineGroupDto with _$TimelineGroupDto {
  const TimelineGroupDto._();

  const factory TimelineGroupDto.encounter({
    required EncounterSummaryDto encounter,
    required List<DocumentSummaryDto> docs,
  }) = TimelineGroupDto_Encounter;
  const factory TimelineGroupDto.document({required DocumentSummaryDto doc}) =
      TimelineGroupDto_Document;
}
