// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_encounter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// 拍前同意记录(医生代拍病人纸质材料流程,Phase 1):由 `ephemeral_create_share`
/// 塞进加密分享包(见 `api::ephemeral`,转换成 `medme_share::share::ShareConsent`)。
/// `method` 为 "signature" 时 `signature_png_base64` 应为 `Some`(手写签名 PNG 的
/// base64);"press_hold"(按住 3 秒确认的兜底手势)时为 `None`。
class ConsentDto {
  final String utcTs;
  final String consentTextVersion;
  final String? signaturePngBase64;
  final String method;
  final String sessionId;

  const ConsentDto({
    required this.utcTs,
    required this.consentTextVersion,
    this.signaturePngBase64,
    required this.method,
    required this.sessionId,
  });

  @override
  int get hashCode =>
      utcTs.hashCode ^
      consentTextVersion.hashCode ^
      signaturePngBase64.hashCode ^
      method.hashCode ^
      sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConsentDto &&
          runtimeType == other.runtimeType &&
          utcTs == other.utcTs &&
          consentTextVersion == other.consentTextVersion &&
          signaturePngBase64 == other.signaturePngBase64 &&
          method == other.method &&
          sessionId == other.sessionId;
}

/// 文档详情:类型/日期(在 document 里)+ 来源文件 + 识别文本。
class DocumentDetailDto {
  final DocumentSummaryDto document;
  final SourceFileMetaDto sourceFile;
  final String ocrText;
  final double? ocrConfidence;
  final String? ocrBackend;

  const DocumentDetailDto({
    required this.document,
    required this.sourceFile,
    required this.ocrText,
    this.ocrConfidence,
    this.ocrBackend,
  });

  @override
  int get hashCode =>
      document.hashCode ^
      sourceFile.hashCode ^
      ocrText.hashCode ^
      ocrConfidence.hashCode ^
      ocrBackend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentDetailDto &&
          runtimeType == other.runtimeType &&
          document == other.document &&
          sourceFile == other.sourceFile &&
          ocrText == other.ocrText &&
          ocrConfidence == other.ocrConfidence &&
          ocrBackend == other.ocrBackend;
}

class DocumentSummaryDto {
  final PlatformInt64 id;
  final String docType;
  final String? docDate;
  final String? docDateEnd;
  final String? title;
  final int pageCount;

  /// 影像检查文档的切片数;非影像文档为 None。
  final int? sliceCount;

  const DocumentSummaryDto({
    required this.id,
    required this.docType,
    this.docDate,
    this.docDateEnd,
    this.title,
    required this.pageCount,
    this.sliceCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      docType.hashCode ^
      docDate.hashCode ^
      docDateEnd.hashCode ^
      title.hashCode ^
      pageCount.hashCode ^
      sliceCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          docType == other.docType &&
          docDate == other.docDate &&
          docDateEnd == other.docDateEnd &&
          title == other.title &&
          pageCount == other.pageCount &&
          sliceCount == other.sliceCount;
}

class EncounterSummaryDto {
  final PlatformInt64 id;
  final String kind;
  final String? provider;
  final String? startDate;
  final String? endDate;
  final String? title;
  final bool transferred;
  final PlatformInt64 docCount;

  const EncounterSummaryDto({
    required this.id,
    required this.kind,
    this.provider,
    this.startDate,
    this.endDate,
    this.title,
    required this.transferred,
    required this.docCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      provider.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      title.hashCode ^
      transferred.hashCode ^
      docCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncounterSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          provider == other.provider &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          title == other.title &&
          transferred == other.transferred &&
          docCount == other.docCount;
}

/// 时间线导出结果:未加密、可打印的自包含 HTML。与 `ShareResultDto` 不同,
/// 没有口令——导出内容不加密,靠系统「分享」sheet 直接交给医生 / 存下来打印。
class ExportResultDto {
  final PlatformInt64 recordCount;
  final PlatformInt64 byteSize;
  final String path;

  const ExportResultDto({
    required this.recordCount,
    required this.byteSize,
    required this.path,
  });

  @override
  int get hashCode => recordCount.hashCode ^ byteSize.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportResultDto &&
          runtimeType == other.runtimeType &&
          recordCount == other.recordCount &&
          byteSize == other.byteSize &&
          path == other.path;
}

/// iCloud 同步状态(设置页开关据此渲染)。`available` = 当前能否解析到 iCloud
/// 容器(iOS-only,由 Dart 侧经 `medme/icloud` MethodChannel 判断后覆盖;Rust
/// 恒返回 false);`enabled` = 本设备是否已开启同步(Rust 据持久标记返回)。
/// 开关/迁移逻辑见 `api::vault` 的 `enable_icloud_sync` / `disable_icloud_sync`。
class IcloudStatusDto {
  final bool available;
  final bool enabled;

  const IcloudStatusDto({required this.available, required this.enabled});

  @override
  int get hashCode => available.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IcloudStatusDto &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          enabled == other.enabled;
}

class ImportOutcomeDto {
  final String name;
  final PlatformInt64 sourceFileId;
  final String status;
  final String? docType;

  /// 本次采集落库的文档 id(前端「待确认」review 队列据此显式标记新导入)。
  /// 去重/失败等没建文档的情况为 None。
  final PlatformInt64? documentId;

  /// 从本份报告文本里识别出的**患者姓名**(`parser::extract_demographics`)。
  /// 前端用它和当前成员档案名字比对——不一致就在「待确认」里标红警告(防导错人)。
  /// 识别不到为 None。
  final String? detectedName;

  const ImportOutcomeDto({
    required this.name,
    required this.sourceFileId,
    required this.status,
    this.docType,
    this.documentId,
    this.detectedName,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      sourceFileId.hashCode ^
      status.hashCode ^
      docType.hashCode ^
      documentId.hashCode ^
      detectedName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportOutcomeDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sourceFileId == other.sourceFileId &&
          status == other.status &&
          docType == other.docType &&
          documentId == other.documentId &&
          detectedName == other.detectedName;
}

/// **iOS PP-OCRv5 测试路径**结果(feat/ios-pp-ocr-test 分支,探索性——ADR 0005
/// 尚未 supersede)。镜像 Dart `OcrResult`(`ocr_bridge.dart`),供
/// `recognize_image_pp` 返回,让真机能对比 Apple Vision vs PP-OCRv5 的识别质量。
class OcrPpResultDto {
  final String text;
  final double confidence;

  const OcrPpResultDto({required this.text, required this.confidence});

  @override
  int get hashCode => text.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrPpResultDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          confidence == other.confidence;
}

class PatientProfileDto {
  final String? name;
  final String? gender;
  final String? birthDate;
  final String? age;
  final PlatformInt64 recordCount;

  const PatientProfileDto({
    this.name,
    this.gender,
    this.birthDate,
    this.age,
    required this.recordCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      gender.hashCode ^
      birthDate.hashCode ^
      age.hashCode ^
      recordCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatientProfileDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          gender == other.gender &&
          birthDate == other.birthDate &&
          age == other.age &&
          recordCount == other.recordCount;
}

/// 二维码分享结果:一条可直接编码成二维码的 URL、带上的疾病数、以及是否仍在
/// 二维码容量内(按构造裁剪后应恒为 true,留作兜底提示)。
class QrShareDto {
  final String url;
  final PlatformInt64 problemCount;
  final bool fitsQr;

  const QrShareDto({
    required this.url,
    required this.problemCount,
    required this.fitsQr,
  });

  @override
  int get hashCode => url.hashCode ^ problemCount.hashCode ^ fitsQr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrShareDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          problemCount == other.problemCount &&
          fitsQr == other.fitsQr;
}

/// 加密分享生成结果:口令(单独告知医生)、记录数、文件字节数、分享文件路径。
class ShareResultDto {
  final String passphrase;
  final PlatformInt64 recordCount;
  final PlatformInt64 byteSize;
  final String path;

  const ShareResultDto({
    required this.passphrase,
    required this.recordCount,
    required this.byteSize,
    required this.path,
  });

  @override
  int get hashCode =>
      passphrase.hashCode ^
      recordCount.hashCode ^
      byteSize.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareResultDto &&
          runtimeType == other.runtimeType &&
          passphrase == other.passphrase &&
          recordCount == other.recordCount &&
          byteSize == other.byteSize &&
          path == other.path;
}

/// 原始文件元信息(文档详情页展示来源 + 前端据此判断是否为图片以渲染缩略)。
class SourceFileMetaDto {
  final PlatformInt64 id;
  final String originalName;
  final String mimeType;
  final PlatformInt64 byteSize;
  final String importedAt;

  const SourceFileMetaDto({
    required this.id,
    required this.originalName,
    required this.mimeType,
    required this.byteSize,
    required this.importedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      originalName.hashCode ^
      mimeType.hashCode ^
      byteSize.hashCode ^
      importedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceFileMetaDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          originalName == other.originalName &&
          mimeType == other.mimeType &&
          byteSize == other.byteSize &&
          importedAt == other.importedAt;
}

@freezed
sealed class TimelineGroupDto with _$TimelineGroupDto {
  const TimelineGroupDto._();

  const factory TimelineGroupDto.encounter({
    required EncounterSummaryDto encounter,
    required List<DocumentSummaryDto> docs,
  }) = TimelineGroupDto_Encounter;
  const factory TimelineGroupDto.document({required DocumentSummaryDto doc}) =
      TimelineGroupDto_Document;
}
