// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ephemeral_cell`, `with_ephemeral`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// 开始一次临时会话:在 `<cache_dir>/ephemeral-<随机>/` 下建全新空箱并打开。
///
/// `cache_dir` 由 Dart 侧传入 iOS `getTemporaryDirectory()`(不进 iCloud 备份,系统
/// 可随时清空——即焚语义与「系统可能替我们清」互为兜底)。会话目录后缀取一次性随机
/// `device_id` 的前 16 位:既避免与其它并发/历史会话撞名,又不必再引入一个独立的
/// 随机源。`device_id` 本身**不落盘、不复用** `machine_device_id`——分享件因此不带
/// 医生本机的设备身份。
Future<void> ephemeralBegin({required String cacheDir}) =>
    RustLib.instance.api.crateApiEphemeralEphemeralBegin(cacheDir: cacheDir);

/// 采集(图片,Flutter 端已识别好文本):镜像 `api::vault::ingest_image_with_text`,
/// 落临时会话箱。
Future<ImportOutcomeDto> ephemeralIngestImageWithText({
  required String name,
  required List<int> bytes,
  required String ocrText,
  required double confidence,
}) => RustLib.instance.api.crateApiEphemeralEphemeralIngestImageWithText(
  name: name,
  bytes: bytes,
  ocrText: ocrText,
  confidence: confidence,
);

/// 采集(字节直传):镜像 `api::vault::ingest_bytes`,落临时会话箱。
Future<ImportOutcomeDto> ephemeralIngestBytes({
  required String filename,
  required List<int> data,
}) => RustLib.instance.api.crateApiEphemeralEphemeralIngestBytes(
  filename: filename,
  data: data,
);

/// 预览时间线:镜像 `api::vault::load_archive`,给医生在交付前核对这次代拍收了
/// 什么、分类对不对。
Future<List<TimelineGroupDto>> ephemeralLoadPreview() =>
    RustLib.instance.api.crateApiEphemeralEphemeralLoadPreview();

/// 打包成加密分享件(带拍前同意记录),写进**临时会话箱**的 `shares/`——不是医生
/// 自己的 vault。`consent` 转换见 `From<ConsentDto>`。
Future<ShareResultDto> ephemeralCreateShare({
  required PlatformInt64 expiresDays,
  required ConsentDto consent,
}) => RustLib.instance.api.crateApiEphemeralEphemeralCreateShare(
  expiresDays: expiresDays,
  consent: consent,
);

/// 即焚:关掉这次会话的 db/日志句柄(`drop`),再整棵删掉它的会话根目录
/// (CAS 原字节 + 事件日志 + db/wal/shm + OCR 文本 + 生成的 share html 全在这棵目录下,
/// 一次 `remove_dir_all` 清干净)。cell 置空。用户取消 / 交付完成 / 路由 dispose 兜底
/// 都调这个,幂等——未开始过会话时是 no-op。
Future<void> ephemeralWipe() =>
    RustLib.instance.api.crateApiEphemeralEphemeralWipe();

/// 启动时清崩溃残留:遍历 `<cache_dir>` 下所有 `ephemeral-*` 前缀目录并删除。
/// App 启动(`main()`,`RustLib.init()` 之后)调一次。不依赖当前进程是否持有某个
/// cell(上次进程崩溃/被系统杀掉时,`ephemeral_wipe` 根本没机会跑,残留只能靠这个
/// 兜底 + iOS 系统本就可能随时清空 `getTemporaryDirectory()` 双保险)。
Future<void> ephemeralSweep({required String cacheDir}) =>
    RustLib.instance.api.crateApiEphemeralEphemeralSweep(cacheDir: cacheDir);
