// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// P1 冒烟:证明现有 Rust 数据核(core-model)能经 FRB 从 Flutter 调通。
/// 在给定目录打开一个保险箱(不存在则新建),返回时间线记录数。
/// 后续 P2 会把 load_archive / ingest / share / export 等全量 API 都接进来。
Future<String> vaultSmoke({required String dir}) =>
    RustLib.instance.api.crateApiSimpleVaultSmoke(dir: dir);
