// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detected_name_for`, `doc_summary`, `ephemeral_cell`, `gather_ephemeral_docs`, `ingest_one`, `proxy_lab_from_json`, `proxy_med_from_json`, `proxy_summary_from_json`, `with_ephemeral`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EphemeralSourceDoc`, `EphemeralState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// 开始一次临时会话:在 `<cache_dir>/ephemeral-<随机>/` 下建全新空箱并打开。
///
/// `cache_dir` 由 Dart 侧传入 `getTemporaryDirectory()`(不进 iCloud/云备份,系统
/// 可随时清空——即焚语义与「系统可能替我们清」互为兜底)。会话目录后缀取一次性
/// 随机 `device_id` 的前 16 位:既避免与其它并发/历史会话撞名,又不必再引入一个
/// 独立的随机源。`device_id` 本身**不落盘、不复用** `machine_device_id`——分享件
/// 因此不带医生本机的设备身份。
Future<void> ephemeralBegin({required String cacheDir}) => RustLib.instance.api
    .crateApiVaultEphemeralEphemeralBegin(cacheDir: cacheDir);

/// 采集(字节直传,如「选择文件」拿到的 PDF/TXT):与 `vault.rs::ingest_bytes` 同
/// 落库语义(逐段复制),落临时会话箱。
Future<ImportOutcomeDto> ephemeralIngestBytes({
  required String filename,
  required List<int> data,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralIngestBytes(
  filename: filename,
  data: data,
);

/// 采集(图片,Flutter 端已用现有 `recognizeImageText`——iOS Vision/PP-OCR、安卓
/// ML Kit——识别好文本):与 `vault.rs::ingest_image_with_text` 同落库语义
/// (逐段复制),落临时会话箱。**本函数不碰任何 OCR 逻辑**,只接收调用方已识别好
/// 的文本 + 置信度。
Future<ImportOutcomeDto> ephemeralIngestImageWithText({
  required String name,
  required List<int> bytes,
  required String ocrText,
  required double confidence,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralIngestImageWithText(
  name: name,
  bytes: bytes,
  ocrText: ocrText,
  confidence: confidence,
);

/// 预览时间线:与 `vault.rs::load_archive` 同逻辑(逐段复制),给医生在交付前
/// 核对这次代拍收了什么、分类对不对。
Future<List<TimelineGroupDto>> ephemeralLoadPreview() =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralLoadPreview();

/// 一份文档的识别文本(供审阅屏「逐份识别内容」摊开展示,复用
/// `widgets/report_content.dart` 的 `ReportContent` 渲染)。与 `vault.rs::get_document`
/// 同取法(逐段复制:只取 `ocr_text` 一项,不需要 `DocumentDetailDto` 的其它字段)。
Future<String> ephemeralDocumentText({required PlatformInt64 documentId}) =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralDocumentText(
      documentId: documentId,
    );

/// 删掉这次代拍收错/拍花的一份文档。与 `vault.rs::delete_document` 同逻辑(逐字
/// 复制):追加 `DocumentDeleted` 事件 → 重放,原始字节留在 CAS。调用方(审阅屏)
/// 删后需自行重新拉 `ephemeral_load_preview` + `ephemeral_summary` 刷新展示。
Future<void> ephemeralDeleteDocument({required PlatformInt64 documentId}) =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralDeleteDocument(
      documentId: documentId,
    );

/// 「病情摘要卡」:在治的病 + 关键化验 + 在用药,给医生三十秒看懂这次代拍收上来的
/// 大局。复用 `parser::assemble_summary`——与生成加密分享跑的**同一套**确定性装配
/// 逻辑(见 `ephemeral_create_share`/`build_encrypted_share_with_consent`),不是另
/// 写一遍抽取。
Future<ProxySummaryDto> ephemeralSummary() =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralSummary();

/// 打包成自包含加密 HTML(带拍前同意记录),写进**临时会话箱**的 `shares/`——
/// 不是医生自己的 vault。与 `vault.rs::create_share` 同逻辑(逐段复制),唯一
/// 差异是永远经 `medme_share::share::build_encrypted_share_with_consent` 传入
/// `consent`(该函数是纯加法,不影响 `vault.rs::create_share` 走的
/// `build_encrypted_share` 原路径)。
Future<ShareResultDto> ephemeralCreateShare({
  required PlatformInt64 expiresDays,
  required ConsentDto consent,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralCreateShare(
  expiresDays: expiresDays,
  consent: consent,
);

/// 即焚:关掉这次会话的 db/日志句柄(`drop`),再整棵删掉它的会话根目录
/// (CAS 原字节 + 事件日志 + db/wal/shm + OCR 文本 + 生成的 share html 全在这棵目录下,
/// 一次 `remove_dir_all` 清干净)。cell 置空。用户取消 / 交付完成 / 路由 dispose 兜底
/// 都调这个,幂等——未开始过会话时是 no-op。
Future<void> ephemeralWipe() =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralWipe();

/// 启动时清崩溃残留:遍历 `<cache_dir>` 下所有 `ephemeral-*` 前缀目录并删除。
/// App 启动(`main()`,`RustLib.init()` 之后)调一次。不依赖当前进程是否持有某个
/// cell(上次进程崩溃/被系统杀掉时,`ephemeral_wipe` 根本没机会跑,残留只能靠这个
/// 兜底 + 系统本就可能随时清空 `getTemporaryDirectory()` 双保险)。
Future<void> ephemeralSweep({required String cacheDir}) => RustLib.instance.api
    .crateApiVaultEphemeralEphemeralSweep(cacheDir: cacheDir);
