// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_demo_files`, `detected_name_for`, `doc_summary`, `ingest_one`, `machine_device_id`, `open_resilient_with_fallback`, `resolve_vault_paths`, `vault_cell`, `with_state_mut`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VaultState`

/// 打开(或新建)保险箱。iCloud 容器路径由 **Dart 侧经 MethodChannel 解析后传入**
/// (`icloud_container_dir`,容器根目录;不可用/非 iOS 传 `None`)——避免 Rust 框架
/// 反向链接 app target 的 Swift 符号(Flutter 插件框架不允许,会 archive linker 失败)。
///
/// 是否用 iCloud 布局以持久标记 `<data_dir>/icloud_enabled` 为准(enable/disable 写/删)。
/// 开了标记且传入了容器 → 真相在 `<container>/Documents/vault`、派生库在沙盒;否则本机
/// `<docs_dir>/vault`。在解析出的 truth_root 打开失败则回退本机,绝不因 iCloud 问题崩。
Future<void> openVault({
  required String docsDir,
  required String dataDir,
  String? icloudContainerDir,
}) => RustLib.instance.api.crateApiVaultOpenVault(
  docsDir: docsDir,
  dataDir: dataDir,
  icloudContainerDir: icloudContainerDir,
);

/// 健康档案时间线:就诊组 + 独立文档,按日期倒序(无日期最后)。与桌面/Tauri
/// 移动端的 `load_archive` 同构——复用同一套 core-model 查询。
Future<List<TimelineGroupDto>> loadArchive() =>
    RustLib.instance.api.crateApiVaultLoadArchive();

/// 文档详情:类型/日期 + 来源文件 + 识别文本。与桌面/Tauri 移动端的
/// `get_document` 同构。
Future<DocumentDetailDto> getDocument({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiVaultGetDocument(id: id);

/// 一份来源文件在磁盘上的**绝对路径**(CAS `objects/…` 下的对象文件)。
///
/// 供 iOS「查看原件」路径在读盘前先把可能被 iCloud 逐出的对象物化到本地用:Dart
/// 拿到此路径后经 `medme/icloud` MethodChannel 触发 `startDownloadingUbiquitousItem`
/// 并等待下载完成(见 `AppDelegate.swift` 的 `ensureDownloaded`),再调
/// `read_source_bytes` / `render_dicom_png` 读盘。安卓无 iCloud、不走这一步。
Future<String> sourceFileObjectPath({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiVaultSourceFileObjectPath(id: id);

/// 一份来源文件的原始字节(图片文档据此渲染缩略图/大图)。与桌面/Tauri 移动端的
/// `read_source_bytes` 同构。iOS 上保险箱开了 iCloud 同步时,`objects/` 里的对象可能
/// 被 iCloud 逐出(替换为 `.icloud` 占位符);Dart 侧在调用本函数前已按平台先经
/// `source_file_object_path` + `medme/icloud`.`ensureDownloaded` 把对象物化回本地,
/// 故这里保持一次普通读盘(已在本地的对象即快路径,不触发任何网络/下载)。
Future<Uint8List> readSourceBytes({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiVaultReadSourceBytes(id: id);

/// 渲染一份 DICOM 来源文件的锚点切片为 PNG。
///
/// 安全:`apps/mobile_flutter/rust/Cargo.toml` 给 iOS + 安卓两端都关掉了 `dicom`
/// 的 `codecs` 特性(C/C++ JPEG2000/JPEG-LS 解码器,GHSA-24px 的 RCE 面),与
/// Tauri 移动端 `apps/mobile/src-tauri/Cargo.toml` 的取舍完全一致——桌面才需要
/// 子进程隔离渲染(`dicom_subprocess`),移动端直接用 `medme_share` 提供的进程内
/// 渲染器就是安全的(其文档明确写了这点)。不支持的压缩格式返回错误,前端按现有
/// 「无法预览」的降级处理即可。
Future<Uint8List> renderDicomPng({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiVaultRenderDicomPng(id: id);

/// 删除一份文档(用户在 review 队列 / 时间线 / 详情页移除)。追加 `DocumentDeleted`
/// 事件 + 重放,原始字节留在 CAS(见 core-model `delete_document`)。文档不存在 = no-op。
/// 前端删完 `bumpVaultRevision` 刷新即可。
Future<void> deleteDocument({required PlatformInt64 documentId}) =>
    RustLib.instance.api.crateApiVaultDeleteDocument(documentId: documentId);

/// 患者档案头(姓名/性别/年龄/记录数)。与桌面/Tauri 移动端同构。
Future<PatientProfileDto> patientProfile() =>
    RustLib.instance.api.crateApiVaultPatientProfile();

/// 采集:对一个真实文件路径(如系统文件选择器返回的路径)跑 ingest,然后重建
/// 就诊分组。PDF/TXT/DICOM 走 `pipeline::ingest`。
Future<ImportOutcomeDto> ingestFile({required String path}) =>
    RustLib.instance.api.crateApiVaultIngestFile(path: path);

/// 采集(字节直传):Flutter 侧从相机/相册/文件选择器拿到的字节 + 原始文件名。
/// 落到沙盒 data 目录下的一次性临时文件(保留扩展名——`pipeline::mime_for` 靠
/// 扩展名判 MIME/PDF/DICOM)→ 跑 ingest → 重建分组 → 删临时文件。镜像 Tauri 版
/// `ingest_bytes`,只是临时文件目录用 `data_dir`(FRB 没有 `app_cache_dir()`)。
Future<ImportOutcomeDto> ingestBytes({
  required String filename,
  required List<int> data,
}) => RustLib.instance.api.crateApiVaultIngestBytes(
  filename: filename,
  data: data,
);

/// 扫描版 PDF 的 OCR 回填。`ingest_bytes` 对无文本层的 PDF 只 `store_no_text`
/// (移动端未链接 Rust OCR 引擎),文档已存但无文字。Flutter 侧用 `pdfx` 逐页把
/// PDF 渲染成 PNG、走原生图片 OCR(iOS Vision / 安卓 ML Kit)拿到文本后,调本函数
/// 把文本补进该已存文档,使其可搜索、进 summary。
///
/// 只补 `ocr_result`;`doc_type` 暂沿用建档时的文件名分类(用 OCR 文本重分类属质量
/// 提升,另做)。文本为空则报错(调用方不应回填空)。
Future<void> backfillPdfText({
  required PlatformInt64 documentId,
  required String text,
  required double confidence,
}) => RustLib.instance.api.crateApiVaultBackfillPdfText(
  documentId: documentId,
  text: text,
  confidence: confidence,
);

/// 采集(图片,Flutter 端已用 ML Kit 识别好文本):原始字节先入 CAS(与
/// `pipeline::ingest` 一致,去重同一张图);识别出文字则建 document + ocr_result
/// (backend 固定 `OcrBackendKind::MlKit`,置信度取调用方传入值,与识别引擎无关——
/// 只是把「MedMe 侧落库时统一打上 MlKit 标签」这件事从 Rust 端 OCR 迁到 Flutter
/// 端 OCR,记录里如实标注来源);识别为空则退回文件名元数据(`StoredNoText`),
/// 原件仍可见。落库语义逐字镜像 Tauri 版 `ingest_image_via_vision`/
/// `ingest_image_via_mlkit`,只是识别文本来自参数而非本地再跑一次 OCR。
Future<ImportOutcomeDto> ingestImageWithText({
  required String name,
  required List<int> bytes,
  required String ocrText,
  required double confidence,
}) => RustLib.instance.api.crateApiVaultIngestImageWithText(
  name: name,
  bytes: bytes,
  ocrText: ocrText,
  confidence: confidence,
);

/// 端到端加密分享:复用 `medme_share::share::build_encrypted_share`,把全部病历
/// 打包成自包含加密 HTML 写进保险箱 `shares/` 目录,返回口令、记录数、字节数与
/// 文件路径。与桌面/Tauri 移动端同构;安全性说明见 `render_dicom_png` 的 doc
/// (进程内 DICOM 渲染在移动端是安全的,`codecs` 特性已关)。
Future<ShareResultDto> createShare({required PlatformInt64 expiresDays}) =>
    RustLib.instance.api.crateApiVaultCreateShare(expiresDays: expiresDays);

/// 导出时间线:复用 `medme_share::export::build_timeline_html_ranged`,把时间线
/// 渲染成未加密、可打印的自包含 HTML 写进保险箱 `shares/` 目录(与加密分享共用
/// 同一目录——都是本机生成、交给系统分享 sheet 的临时导出件)。
///
/// `from_date` / `to_date` 为可选的 `YYYY-MM-DD`(前端日期选择器传入);任一为空
/// 表示该侧不限,两者都为空即全量导出。`from` 取当天 00:00、`to` 取当天 23:59:59
/// (含端点)。无 `doc_date` 的记录仅在完全不筛选时纳入(见共享 crate 的说明)。
Future<ExportResultDto> exportTimelineHtml({
  String? fromDate,
  String? toDate,
}) => RustLib.instance.api.crateApiVaultExportTimelineHtml(
  fromDate: fromDate,
  toDate: toDate,
);

/// 一键「载入示例数据」:把编译进本 crate 的张建国示例病历(见 `DEMO_DATA`)
/// 批量导入保险箱,让测试者无需手动选文件就能看到 健康档案。按路径排序保证
/// 可复现;`pipeline::ingest` 去重,重复点击安全。返回成功处理的文件数。
///
/// 与 Tauri 版的差异只在「示例数据从哪来」:Tauri 版随 `bundle.resources` 打包、
/// 运行时用 `resource_dir()` 定位;这里没有「应用资源目录」,数据集直接编译进
/// 二进制(`DEMO_DATA`),运行时落一份到 `data_dir` 下的临时目录再喂给
/// `pipeline::ingest`(它按路径操作,不接受内存字节),用完即删。
Future<PlatformInt64> loadDemoData() =>
    RustLib.instance.api.crateApiVaultLoadDemoData();

/// 「清空保险箱 · 重置」:删掉当前真相目录(`truth_root`)+ 派生库
/// (`db_path`),再用 `open_split_resilient` 在同一位置重建。之后 `load_archive`
/// 会返回空。与桌面/Tauri 移动端的 `reset_vault` 同构,包括同一条安全兜底:
/// `truth_root` 必须是一个名为 `vault` 的目录,防止误删沙盒其它内容。
Future<void> resetVault() => RustLib.instance.api.crateApiVaultResetVault();

/// iCloud 同步是否已在本设备开启(读持久标记 `<data_dir>/icloud_enabled`)。
///
/// 分工:`enabled` 由 Rust 据持久标记如实返回;`available`(能否解析到 iCloud 容器)
/// 是 iOS-only 且需原生 API,Rust 拿不到容器,恒返回 `false` 交由 Dart 侧经
/// `medme/icloud` MethodChannel(`IcloudBridge.containerPath`)判断后覆盖。整套 iCloud
/// 开关/迁移逻辑见 `enable_icloud_sync` / `disable_icloud_sync` 与 `open_vault`。
Future<IcloudStatusDto> icloudStatus() =>
    RustLib.instance.api.crateApiVaultIcloudStatus();

/// 开启 iCloud 同步:把保险箱真相迁进 iCloud 容器 `<container_dir>/Documents/vault`,
/// 派生库留沙盒,写持久标记。容器路径由 Dart 经 MethodChannel 解析后传入。迁移用
/// core-model `relocate_to`(搬 objects/log/db/VERSION;容器里已有别设备的 vault 则
/// adopt+merge)——与已验证的 Tauri #38 同一套安全操作。幂等。
Future<void> enableIcloudSync({required String containerDir}) => RustLib
    .instance
    .api
    .crateApiVaultEnableIcloudSync(containerDir: containerDir);

/// 关闭 iCloud 同步:把真相从容器**复制**回本机 `<docs_dir>/vault`(容器副本保留),
/// 本地重开派生库,清标记 + 沙盒 iCloud 派生库。用 `copy_to` 只复制不删源。幂等。
Future<void> disableIcloudSync() =>
    RustLib.instance.api.crateApiVaultDisableIcloudSync();
