// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detected_name_for`, `doc_summary`, `ephemeral_cell`, `gather_ephemeral_docs`, `ingest_one`, `proxy_lab_from_json`, `proxy_med_from_json`, `proxy_summary_from_json`, `with_ephemeral`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EphemeralSourceDoc`, `EphemeralState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// 开始一次临时会话:在 `<cache_dir>/ephemeral-<随机>/` 下建全新空箱并打开。
///
/// `cache_dir` 由 Dart 侧传入 `getTemporaryDirectory()`(不进 iCloud/云备份,系统
/// 可随时清空——即焚语义与「系统可能替我们清」互为兜底)。会话目录后缀取一次性
/// 随机 `device_id` 的前 16 位:既避免与其它并发/历史会话撞名,又不必再引入一个
/// 独立的随机源。`device_id` 本身**不落盘、不复用** `machine_device_id`——分享件
/// 因此不带医生本机的设备身份。
Future<void> ephemeralBegin({required String cacheDir}) => RustLib.instance.api
    .crateApiVaultEphemeralEphemeralBegin(cacheDir: cacheDir);

/// 采集(字节直传,如「选择文件」拿到的 PDF/TXT):与 `vault.rs::ingest_bytes` 同
/// 落库语义(逐段复制),落临时会话箱。
Future<ImportOutcomeDto> ephemeralIngestBytes({
  required String filename,
  required List<int> data,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralIngestBytes(
  filename: filename,
  data: data,
);

/// 采集(图片,Flutter 端已用现有 `recognizeImageText`——iOS Vision/PP-OCR、安卓
/// ML Kit——识别好文本):与 `vault.rs::ingest_image_with_text` 同落库语义
/// (逐段复制),落临时会话箱。**本函数不碰任何 OCR 逻辑**,只接收调用方已识别好
/// 的文本 + 置信度。
Future<ImportOutcomeDto> ephemeralIngestImageWithText({
  required String name,
  required List<int> bytes,
  required String ocrText,
  required double confidence,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralIngestImageWithText(
  name: name,
  bytes: bytes,
  ocrText: ocrText,
  confidence: confidence,
);

/// 预览时间线:与 `vault.rs::load_archive` 同逻辑(逐段复制),给医生在交付前
/// 核对这次代拍收了什么、分类对不对。
Future<List<TimelineGroupDto>> ephemeralLoadPreview() =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralLoadPreview();

/// 一份文档的识别文本(供审阅屏「逐份识别内容」摊开展示,复用
/// `widgets/report_content.dart` 的 `ReportContent` 渲染)。与 `vault.rs::get_document`
/// 同取法(逐段复制:只取 `ocr_text` 一项,不需要 `DocumentDetailDto` 的其它字段)。
Future<String> ephemeralDocumentText({required PlatformInt64 documentId}) =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralDocumentText(
      documentId: documentId,
    );

/// 删掉这次代拍收错/拍花的一份文档。与 `vault.rs::delete_document` 同逻辑(逐字
/// 复制):追加 `DocumentDeleted` 事件 → 重放,原始字节留在 CAS。调用方(审阅屏)
/// 删后需自行重新拉 `ephemeral_load_preview` + `ephemeral_summary` 刷新展示。
Future<void> ephemeralDeleteDocument({required PlatformInt64 documentId}) =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralDeleteDocument(
      documentId: documentId,
    );

/// 「病情摘要卡」:在治的病 + 关键化验 + 在用药,给医生三十秒看懂这次代拍收上来的
/// 大局。复用 `parser::assemble_summary`——与生成加密分享跑的**同一套**确定性装配
/// 逻辑(见 `ephemeral_create_share`/`build_encrypted_share_with_consent_and_confirmed`),
/// 不是另写一遍抽取。**只汇总已确认的文档**(用户拍板的最终流程):医生点开一份核对
/// 无误、点「确认这一份」之前,这份的内容不进摘要——摘要要反映的是「已核实的病情」,
/// 不是「拍了什么就无脑汇总」。未确认文档的原文仍完整躺在待确认列表的详情页,不丢
/// 信息,只是不参与这张卡的装配。
Future<ProxySummaryDto> ephemeralSummary() =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralSummary();

/// 标记/取消一份文档「已确认」(医生在详情页点「确认这一份」;整份确认,不细到
/// 每一项)。存进 [`EphemeralState::confirmed`],随 [`ephemeral_wipe`] 一起清空,
/// 不落盘、不进事件日志。文档不存在也不报错(纯内存 map,置了就置了,采集/预览
/// 侧据实际文档列表展示,不会凭空多出一行)。
Future<void> ephemeralSetConfirmed({
  required PlatformInt64 documentId,
  required bool confirmed,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralSetConfirmed(
  documentId: documentId,
  confirmed: confirmed,
);

/// 当前临时会话箱里每份文档的确认状态(供待确认列表屏渲染「待确认/已确认」标签)。
/// 只返回**显式确认过**的文档;未出现在结果里的 document_id 一律按「待确认」处理
/// (与 [`ephemeral_summary`] 的默认值语义一致)。
Future<List<ConfirmedStatusDto>> ephemeralConfirmedMap() =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralConfirmedMap();

/// 一份文档详情(供待确认列表「点进一份」的详情页):类型/日期 + 来源文件元信息 +
/// 识别文本 + 置信度。与 `vault.rs::get_document` 同取法(逐段复制),唯一差异是
/// **没有 iCloud 物化步骤**——临时会话目录是系统临时缓存目录下的一次性子目录,不在
/// iCloud 同步的 `docs/vault/profiles` 子树下,永远是本地磁盘、不会被 iCloud 逐出。
Future<DocumentDetailDto> ephemeralGetDocument({
  required PlatformInt64 documentId,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralGetDocument(
  documentId: documentId,
);

/// 一份来源文件的原始字节(详情页「查看原件」渲染图片/PDF)。与
/// `vault.rs::read_source_bytes` 同逻辑(逐段复制),无需 iCloud 物化(见
/// [`ephemeral_get_document`] 的说明)。
Future<Uint8List> ephemeralReadSourceBytes({
  required PlatformInt64 sourceFileId,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralReadSourceBytes(
  sourceFileId: sourceFileId,
);

/// 渲染一份 DICOM 来源文件的锚点切片为 PNG。与 `vault.rs::render_dicom_png` 同逻辑
/// (逐段复制)。
Future<Uint8List> ephemeralRenderDicomPng({
  required PlatformInt64 sourceFileId,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralRenderDicomPng(
  sourceFileId: sourceFileId,
);

/// 打包成自包含加密 HTML(带拍前同意记录),写进**临时会话箱**的 `shares/`——
/// 不是医生自己的 vault。与 `vault.rs::create_share` 同逻辑(逐段复制),差异有二:
/// (a) 永远经 `medme_share::share::build_encrypted_share_with_consent_and_confirmed`
/// 传入 `consent`(该函数是纯加法,不影响 `vault.rs::create_share` 走的
/// `build_encrypted_share` 原路径);(b) 把当前已确认的 document_id 集合一并传入——
/// **所有原件都进分享包**(未确认的也在,病人拿到手上原件不缺一份),但 payload 里
/// 只有确认过的那些参与 summary 装配,且每条 record 都带一个 `confirmed` 标记(供
/// 病人侧 Phase 3 后续「认领后再确认」用,本次只加这个字段、不做患者侧交互)。
Future<ShareResultDto> ephemeralCreateShare({
  required PlatformInt64 expiresDays,
  required ConsentDto consent,
}) => RustLib.instance.api.crateApiVaultEphemeralEphemeralCreateShare(
  expiresDays: expiresDays,
  consent: consent,
);

/// 即焚:关掉这次会话的 db/日志句柄(`drop`),再整棵删掉它的会话根目录
/// (CAS 原字节 + 事件日志 + db/wal/shm + OCR 文本 + 生成的 share html 全在这棵目录下,
/// 一次 `remove_dir_all` 清干净)。cell 置空。用户取消 / 交付完成 / 路由 dispose 兜底
/// 都调这个,幂等——未开始过会话时是 no-op。
Future<void> ephemeralWipe() =>
    RustLib.instance.api.crateApiVaultEphemeralEphemeralWipe();

/// 启动时清崩溃残留:遍历 `<cache_dir>` 下所有 `ephemeral-*` 前缀目录并删除。
/// App 启动(`main()`,`RustLib.init()` 之后)调一次。不依赖当前进程是否持有某个
/// cell(上次进程崩溃/被系统杀掉时,`ephemeral_wipe` 根本没机会跑,残留只能靠这个
/// 兜底 + 系统本就可能随时清空 `getTemporaryDirectory()` 双保险)。
Future<void> ephemeralSweep({required String cacheDir}) => RustLib.instance.api
    .crateApiVaultEphemeralEphemeralSweep(cacheDir: cacheDir);
